"""unidades: estacionamiento discapacitados

Revision ID: 0894547e0b85
Revises: b5410b33575e
Create Date: 2026-07-15 21:50:25.725770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0894547e0b85'
down_revision: Union[str, None] = 'b5410b33575e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unidades', sa.Column('estacionamiento_discapacitados', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unidades', 'estacionamiento_discapacitados')
    # ### end Alembic commands ###
