"""gastos comunes: extraordinario por torre/sector

Revision ID: 1cd81c8d8680
Revises: efddcc93d1de
Create Date: 2026-07-15 13:56:25.119553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1cd81c8d8680'
down_revision: Union[str, None] = 'efddcc93d1de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('periodos_gasto_comun', sa.Column('extraordinario_torre', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('periodos_gasto_comun', 'extraordinario_torre')
    # ### end Alembic commands ###
