"""residentes: estacionamiento y bodega; condominio: estacionamientos visita; visita: numero estacionamiento

Revision ID: 371d949b1275
Revises: e10c9fd5eb68
Create Date: 2026-07-15 19:40:58.009870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '371d949b1275'
down_revision: Union[str, None] = 'e10c9fd5eb68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('condominios', sa.Column('estacionamientos_visita', sa.Integer(), nullable=True))
    op.add_column('residentes', sa.Column('numero_estacionamiento', sa.String(length=50), nullable=True))
    op.add_column('residentes', sa.Column('numero_bodega', sa.String(length=50), nullable=True))
    op.add_column('visitas', sa.Column('numero_estacionamiento', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visitas', 'numero_estacionamiento')
    op.drop_column('residentes', 'numero_bodega')
    op.drop_column('residentes', 'numero_estacionamiento')
    op.drop_column('condominios', 'estacionamientos_visita')
    # ### end Alembic commands ###
