"""eliminar numero_bodega de residentes, agregar considerar_bodega a gasto comun

Revision ID: 41d69f52dbdc
Revises: b085fcfa894d
Create Date: 2026-07-15 20:29:01.419081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '41d69f52dbdc'
down_revision: Union[str, None] = 'b085fcfa894d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'periodos_gasto_comun',
        sa.Column('considerar_bodega', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('periodos_gasto_comun', 'considerar_bodega', server_default=None)
    op.drop_column('residentes', 'numero_bodega')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('residentes', sa.Column('numero_bodega', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('periodos_gasto_comun', 'considerar_bodega')
    # ### end Alembic commands ###
