"""gastos comunes: periodos y cargos por unidad

Revision ID: 7595e674bf36
Revises: b82edae2ae8f
Create Date: 2026-07-14 14:28:11.850128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7595e674bf36'
down_revision: Union[str, None] = 'b82edae2ae8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periodos_gasto_comun',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('condominio_id', sa.UUID(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('tarifa_m2', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('extraordinario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('condominio_id', 'anio', 'mes', name='uq_periodo_condominio_anio_mes')
    )
    op.create_table('cargos_unidad',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('periodo_id', sa.UUID(), nullable=False),
    sa.Column('unidad_id', sa.UUID(), nullable=False),
    sa.Column('monto_base', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monto_extraordinario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pagado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos_gasto_comun.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unidad_id'], ['unidades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cargos_unidad')
    op.drop_table('periodos_gasto_comun')
    # ### end Alembic commands ###
