"""vehiculos vinculados a unidad

Revision ID: 7b85011ccf5e
Revises: d6822c461379
Create Date: 2026-07-15 10:05:28.687206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7b85011ccf5e'
down_revision: Union[str, None] = 'd6822c461379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehiculos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('condominio_id', sa.UUID(), nullable=False),
    sa.Column('unidad_id', sa.UUID(), nullable=False),
    sa.Column('patente', sa.String(length=15), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unidad_id'], ['unidades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('condominio_id', 'patente', name='uq_vehiculo_condominio_patente')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehiculos')
    # ### end Alembic commands ###
