"""encomiendas: llegada notificacion retiro

Revision ID: 7c4e9f5e94aa
Revises: 7b85011ccf5e
Create Date: 2026-07-15 10:32:44.668151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7c4e9f5e94aa'
down_revision: Union[str, None] = '7b85011ccf5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encomiendas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('condominio_id', sa.UUID(), nullable=False),
    sa.Column('unidad_id', sa.UUID(), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'RETIRADO', name='estado_encomienda'), nullable=False),
    sa.Column('fecha_llegada', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_retiro', sa.DateTime(), nullable=True),
    sa.Column('retirado_por', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unidad_id'], ['unidades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('encomiendas')
    # ### end Alembic commands ###
