"""turnos de guardias de seguridad

Revision ID: ad0358dabdc2
Revises: 7c4e9f5e94aa
Create Date: 2026-07-15 10:51:00.965151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ad0358dabdc2'
down_revision: Union[str, None] = '7c4e9f5e94aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turnos_guardia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('condominio_id', sa.UUID(), nullable=False),
    sa.Column('nombre_guardia', sa.String(length=200), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('dia_semana', sa.Enum('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', 'DOMINGO', name='dia_semana'), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turnos_guardia')
    # ### end Alembic commands ###
