"""unidades: numero y metraje de bodega

Revision ID: b085fcfa894d
Revises: 371d949b1275
Create Date: 2026-07-15 20:01:30.475938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b085fcfa894d'
down_revision: Union[str, None] = '371d949b1275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unidades', sa.Column('numero_bodega', sa.String(length=50), nullable=True))
    op.add_column('unidades', sa.Column('metraje_bodega', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unidades', 'metraje_bodega')
    op.drop_column('unidades', 'numero_bodega')
    # ### end Alembic commands ###
