"""residentes: agregar apellido

Revision ID: b5410b33575e
Revises: 41d69f52dbdc
Create Date: 2026-07-15 21:21:50.114547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b5410b33575e'
down_revision: Union[str, None] = '41d69f52dbdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('residentes', sa.Column('apellido', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('residentes', 'apellido')
    # ### end Alembic commands ###
