"""registro de pagos con reversion

Revision ID: c71da67cb6db
Revises: 7595e674bf36
Create Date: 2026-07-14 15:36:37.083654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c71da67cb6db'
down_revision: Union[str, None] = '7595e674bf36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('condominio_id', sa.UUID(), nullable=False),
    sa.Column('cargo_id', sa.UUID(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo', sa.Enum('TRANSFERENCIA', 'EFECTIVO', 'WEBPAY', name='metodo_pago'), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('reversado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargos_unidad.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagos')
    # ### end Alembic commands ###
