"""comunicados con prioridad

Revision ID: ce091769942e
Revises: d7734e2b059b
Create Date: 2026-07-14 19:54:37.344191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ce091769942e'
down_revision: Union[str, None] = 'd7734e2b059b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comunicados',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('condominio_id', sa.UUID(), nullable=False),
    sa.Column('autor_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('prioridad', sa.Enum('NORMAL', 'IMPORTANTE', 'URGENTE', name='prioridad_comunicado'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comunicados')
    # ### end Alembic commands ###
