"""finanzas: movimientos manuales de ingresos y egresos

Revision ID: d6525b0ec100
Revises: c71da67cb6db
Create Date: 2026-07-14 17:25:10.078532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd6525b0ec100'
down_revision: Union[str, None] = 'c71da67cb6db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimientos_financieros',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('condominio_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('INGRESO', 'EGRESO', name='tipo_movimiento'), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimientos_financieros')
    # ### end Alembic commands ###
