"""control de visitas con alerta de horas

Revision ID: d6822c461379
Revises: ce091769942e
Create Date: 2026-07-14 20:02:30.205097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd6822c461379'
down_revision: Union[str, None] = 'ce091769942e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('condominio_id', sa.UUID(), nullable=False),
    sa.Column('unidad_id', sa.UUID(), nullable=False),
    sa.Column('nombre_visitante', sa.String(length=200), nullable=False),
    sa.Column('rut_visitante', sa.String(length=20), nullable=True),
    sa.Column('hora_entrada', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('hora_salida', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unidad_id'], ['unidades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitas')
    # ### end Alembic commands ###
