"""multas ligadas a finanzas

Revision ID: d7734e2b059b
Revises: d6525b0ec100
Create Date: 2026-07-14 18:36:58.769501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd7734e2b059b'
down_revision: Union[str, None] = 'd6525b0ec100'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('condominio_id', sa.UUID(), nullable=False),
    sa.Column('unidad_id', sa.UUID(), nullable=False),
    sa.Column('movimiento_id', sa.UUID(), nullable=False),
    sa.Column('motivo', sa.String(length=300), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('pagada', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movimiento_id'], ['movimientos_financieros.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unidad_id'], ['unidades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movimiento_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('multas')
    # ### end Alembic commands ###
