"""residentes: email, condominios: comuna ciudad imagen

Revision ID: e10c9fd5eb68
Revises: 1cd81c8d8680
Create Date: 2026-07-15 17:53:02.418234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e10c9fd5eb68'
down_revision: Union[str, None] = '1cd81c8d8680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('condominios', sa.Column('comuna', sa.String(length=100), nullable=True))
    op.add_column('condominios', sa.Column('ciudad', sa.String(length=100), nullable=True))
    op.add_column('condominios', sa.Column('imagen_url', sa.String(length=500), nullable=True))
    op.add_column('residentes', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('residentes', 'email')
    op.drop_column('condominios', 'imagen_url')
    op.drop_column('condominios', 'ciudad')
    op.drop_column('condominios', 'comuna')
    # ### end Alembic commands ###
