"""mover estacionamiento discapacitados de unidad a condominio

Revision ID: e17799060a9e
Revises: 0894547e0b85
Create Date: 2026-07-16 18:06:51.157010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e17799060a9e'
down_revision: Union[str, None] = '0894547e0b85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('condominios', sa.Column('estacionamientos_discapacitados', sa.Integer(), nullable=True))
    op.drop_column('unidades', 'estacionamiento_discapacitados')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unidades', sa.Column('estacionamiento_discapacitados', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('condominios', 'estacionamientos_discapacitados')
    # ### end Alembic commands ###
