"""proveedores: directorio de servicios externos

Revision ID: efddcc93d1de
Revises: ad0358dabdc2
Create Date: 2026-07-15 10:55:26.969662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'efddcc93d1de'
down_revision: Union[str, None] = 'ad0358dabdc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('condominio_id', sa.UUID(), nullable=False),
    sa.Column('nombre_empresa', sa.String(length=200), nullable=False),
    sa.Column('rubro', sa.String(length=100), nullable=False),
    sa.Column('contacto_nombre', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proveedores')
    # ### end Alembic commands ###
